### PR TITLE
Fix an exception while installing server.(Server returns HTTP 403 code.)

### PR DESCRIPTION
**Pull request by Romonov**
It might only occur on China developers, because of the GFW.

### CODE REVIEW

**Comment by modmuss50** [comment]
Im not sure what the issue you are fixing is?

And is it possible to fix using native java? having a lib just for downloading files is a bit of a waste tbh.

**Comment by Romonov** [comment]
[exception](https://i.loli.net/2019/04/29/5cc7110f0a223.jpg)

When i use the install, i always have this problem.
But use the commons-io will solve this problem.

**Comment by modmuss50** [comment]
Have you tried in the last 20 or so mins? as I was messing around with some server settings, that I have now reverted. I would be happier with a native fix, we may need to encode the URL?

**Comment by 3TUSK** [comment]
@Romonov Have you tried download the said file from that link directly?

**Comment by Romonov** [comment]
> @Romonov Have you tried download the said file from that link directly?

Yes, i have tried it.

**Comment by liach** [comment]
Good to hear that fabric is accessible in China. Would give it an advantage over forge for sure!

**Comment by 3TUSK** [comment]
Welp I have confirmed that link is accessible in mainland China as well.  

> Good to hear that fabric is accessible in China.

Does not imply high speed.

**Pull request closed without merging**
