### PR TITLE
fix the hard-coded manifest

### PR DESCRIPTION
**Pull request by LogicFan**

### CODE REVIEW

**Review by sfPlayer1 — APPROVED** [review]
LGTM, thanks!

minor nit: manifestDir should be manifestPath

also worth considering to rename mainClassManifest to jarMainClass and mainClassMeta to launchMainClass - going for usage over data source

**Comment by LogicFan** [comment]
Hi, any update on this?

**Review by sfPlayer1 — APPROVED** [review]

**Comment by LogicFan** [comment]
@modmuss50  Hi, just a friendly reminder so you don't forget this PR.

**Comment by LogicFan** [comment]
Any ETA when this one will be merged?

**Comment by sfPlayer1** [comment]
Once modmuss had a chance to take a look, we were a bit distracted with Mixin and other issues

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
