### PR TITLE
W.I.P translation to polish

### PR DESCRIPTION
**Pull request by kotelkonrad**

### CODE REVIEW

**Comment by modmuss50** [comment]
Are these still WIP?

**Comment by liach** [comment]
Need @asiekierka to review this

**Comment by haykam821** [comment]
This should probably be marked as a draft if the translations are still WIP.

However, I don't think @kotelkonrad will be finishing them because their commit graph has gone dark.

**Comment by modmuss50** [comment]
Superseeded by #40

**Pull request closed without merging**
